language: python

python:
  - "3.6"

install:
  - pip install --upgrade pip
  - pip install git+https://github.com/vmware/pyvcloud.git
  - pip install -r requirements.txt
  - pip install -e .
  - python setup.py install
  - pip install tox

script:
  - tox -e flake8
  - pip list --format=columns | grep pyvcloud
  - python -c 'import pkg_resources; print(pkg_resources.require("pyvcloud")[0].version)'
  - pip list --format=columns | grep vcd-cli
  - python -c 'import pkg_resources; print(pkg_resources.require("vcd-cli")[0].version)'
  - vcd version
